//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manulife.TopFiveWebsites.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitLogExclusion
    {
        public long id { get; set; }
        public string host { get; set; }
        public Nullable<System.DateTime> excludedSince { get; set; }
        public Nullable<System.DateTime> excludedTill { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
    }
}
